# Generated by Django 4.2.3 on 2023-09-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0002_alter_engineers_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahdaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engineer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineers')),
            ],
        ),
        migrations.CreateModel(
            name='Masourfat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_masrouf', models.DateField(blank=True, null=True)),
                ('almardeen', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('bain_masrouf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineers')),
            ],
        ),
        migrations.CreateModel(
            name='Mostakhlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_mostakhlas', models.DateField(blank=True, null=True)),
                ('workforce', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Combined_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engineering_stamp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_mostakhlas_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_extract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altaminat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_session', models.DateField(blank=True, null=True)),
                ('date_finance', models.DateField(blank=True, null=True)),
                ('date_notification_Altrsih', models.DateField(blank=True, null=True)),
                ('date_sadad_khatab_alkhsmat', models.DateField(blank=True, null=True)),
                ('date_asnad', models.DateField(blank=True, null=True)),
                ('date_work', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_extra_end', models.IntegerField(default=0)),
                ('duration_project', models.IntegerField(blank=True, null=True)),
                ('price_project', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gramat_altakheer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report', models.TextField(null=True)),
                ('ahdaa', models.ManyToManyField(blank=True, to='projects.ahdaa')),
                ('masourfats', models.ManyToManyField(blank=True, to='projects.masourfat')),
                ('mostakhlas', models.ManyToManyField(blank=True, to='projects.mostakhlas')),
            ],
        ),
    ]
