# Generated by Django 4.2.3 on 2023-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_session', models.DateField(blank=True, null=True)),
                ('date_finance', models.DateField(blank=True, null=True)),
                ('date_notification_Altrsih', models.DateField(blank=True, null=True)),
                ('date_sadad_khatab_alkhsmat', models.DateField(blank=True, null=True)),
                ('date_asnad', models.DateField(blank=True, null=True)),
                ('date_work', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_extra_end', models.DateField(blank=True, null=True)),
                ('time_project', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
