# Generated by Django 4.2.3 on 2023-09-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_alter_engineers_job_title'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostakhlas',
            name='name',
        ),
        migrations.AddField(
            model_name='mostakhlas',
            name='engineer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineers'),
        ),
    ]
