# Generated by Django 4.2.3 on 2023-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_mostakhlas_name_mostakhlas_engineer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostakhlas',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
