# Generated by Django 4.1.6 on 2023-09-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_mostakhlas_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='insurance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
