# Generated by Django 4.1.6 on 2023-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_insurance_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_increase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_Period', models.DateField(blank=True, null=True)),
                ('terminationBeforeTheIncrease', models.DateField(blank=True, null=True)),
                ('terminationAfterTheIncrease', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
