# Generated by Django 4.1.6 on 2023-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_additionalperiods'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='durations',
            field=models.ManyToManyField(blank=True, to='projects.additionalperiods'),
        ),
    ]
