# Generated by Django 4.2.3 on 2023-10-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0001_initial'),
        ('projects', '0007_mostakhlas_applied_tear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masourfat',
            name='almardeen',
        ),
        migrations.AddField(
            model_name='masourfat',
            name='imported',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imported.imported'),
        ),
    ]
