# Generated by Django 4.2.3 on 2023-10-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_masourfat_almardeen_masourfat_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='letter_of_guarantee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
