# Generated by Django 4.2.3 on 2023-10-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0001_initial'),
        ('projects', '0009_projects_letter_of_guarantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostsImported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('imported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imported.imported')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='costs_importeds',
            field=models.ManyToManyField(blank=True, to='projects.costsimported'),
        ),
    ]
