# Generated by Django 4.2.3 on 2023-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_costsimported_projects_costs_importeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahdaa',
            name='date_ahdaa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostakhlas',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
