# Generated by Django 4.2.3 on 2023-10-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projects_letter_of_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_write_projects', 'Can write Projects')]},
        ),
    ]
