# Generated by Django 4.2.3 on 2023-10-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
    ]
