# Generated by Django 4.2.3 on 2023-10-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalperiods',
            options={'permissions': [('view_report', 'Can do view report Periods')]},
        ),
        migrations.AlterModelOptions(
            name='ahdaa',
            options={'permissions': [('view_report', 'Can do view report ahdaa')]},
        ),
        migrations.AlterModelOptions(
            name='masourfat',
            options={'permissions': [('view_report', 'Can do view report imported')]},
        ),
        migrations.AlterModelOptions(
            name='mostakhlas',
            options={'permissions': [('view_report', 'Can do view report Mostakhlas'), ('view_report2', 'Can do view report Mostakhlas')]},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('view_report', 'Can do view report project'), ('view_details', 'Can do view report details'), ('view_finance', 'Can do view report finance')]},
        ),
    ]
