# Generated by Django 4.2.3 on 2023-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_additionalperiods_options_alter_ahdaa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_price_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
