# Generated by Django 4.2.3 on 2023-10-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0002_alter_imported_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imported',
            options={},
        ),
    ]
