# Generated by Django 4.2.3 on 2023-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField(max_length=4)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
