# Generated by Django 4.2.3 on 2023-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineers',
            name='job_title',
            field=models.CharField(max_length=10),
        ),
    ]
