# Generated by Django 4.2.3 on 2023-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_alter_engineers_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineers',
            name='graduation_year',
            field=models.IntegerField(),
        ),
    ]
